config/routes.rb
Rails.application.routes.draw do
  resources :surveys
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "surveys#new"

  resources :voters, only: [:edit, :update], param: :token
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  validates :name, presence: true
  validates_db_uniqueness_of :name, scope: :survey_id, rescue: :always

  has_many :ratings
  belongs_to :survey

  Rating::NAMES.keys.each do |rating_name|
    define_method("#{rating_name.parameterize.underscore}_percent") do
      return 0 if ratings.none?

      (ratings.public_send(rating_name.parameterize.underscore).count.to_f / ratings.count.to_f * 100).round(1)
    end
  end

  def score
    @score ||= Score.for(self)
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :voter
  belongs_to :proposal

  validates :name, :proposal_id, :voter_id, presence: true

  NAMES = {
    "excellent" => 7,
    "very good" => 6,
    "good" => 5,
    "passable" => 4,
    "inadequate" => 3
  }

  enum name: NAMES
end

app/models/score.rb
class Score
  # The name of the rating with an absolute majority for one's proposal
  attr_reader :name
  # The value of the rating with an absolute majority
  attr_reader :value
  # the amount of people who voted for at least this rating
  attr_reader :rating_count
  # the sum of all ratings value
  attr_reader :rating_sum
  # the proposal associated to the score
  attr_reader :proposal

  def initialize(proposal)
    @rating_count = 0

    @name = proposal.ratings.order(name: :desc).pluck(:name).tally.find do |name, amount|
      @rating_count += amount
      rating_count > proposal.survey.number_of_votes / 2
    end.first

    @value = Rating::NAMES[name]
    @proposal = proposal
    @rating_sum = proposal.ratings.sum(:name)
  end

  def <=>(other)
    return other.value <=> self.value if (other.value <=> self.value) != 0
    return other.rating_count <=> self.rating_count if (other.rating_count <=> self.rating_count) != 0

    other.rating_sum <=> self.rating_sum
  end

  def self.for(proposal)
    return NullScore.new(proposal) if proposal.ratings.none?

    Score.new(proposal)
  end

  class NullScore < Score
    def initialize(proposal)
      @name = "Waiting for votes"
      @value = -1
      @rating_count = 0
      @rating_sum = 0
      @proposal = proposal
    end
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  validates :name, presence: true
  validates :proposals, length: { minimum: 2 }, on: :update
  validates :voters, length: { minimum: 2 }, on: :update

  has_many :proposals
  has_many :voters
  has_many :ratings, through: :proposals

  accepts_nested_attributes_for :proposals, allow_destroy: true
  accepts_nested_attributes_for :voters, allow_destroy: true

  def number_of_votes
    return 0 unless proposals.count > 0

    ratings.count / proposals.count
  end

  def winner
    @winner ||= ratings.none? ? "No winner yet" : scores.first.proposal.name
  end

  def scores
    @scores ||= proposals.map(&:score).sort
  end
end

app/models/voter.rb
class Voter < ApplicationRecord
  validates :email, presence: true, email: true
  validates_db_uniqueness_of :email, scope: :survey_id, rescue: :always

  has_secure_token

  after_commit :send_invitation_link, on: :create

  belongs_to :survey
  has_many :ratings

  accepts_nested_attributes_for :ratings

  private

  def send_invitation_link
    VoterMailer.with(voter: self).invitation_email.deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show edit update destroy ]

  # GET /surveys or /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1 or /surveys/1.json
  def show
    @proposals = @survey.proposals
    @voters = @survey.voters

    if @proposals.none? || @voters.none?
      redirect_to edit_survey_url(@survey), notice: "you need to add voters and proposals before checking the results"
    end
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
    if @survey.proposals.count == 0 && @survey.voters.count == 0
      2.times { @survey.proposals.build }
      2.times { @survey.voters.build }
    else
      redirect_to survey_url(@survey)
    end
  end

  # POST /surveys or /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to edit_survey_url(@survey), notice: "Survey was successfully created." }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1 or /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully updated." }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1 or /surveys/1.json
  def destroy
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:name, proposals_attributes: [:id, :name, :_destroy], voters_attributes: [:id, :email, :_destroy])
    end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController

  before_action :set_voter, only: %i[  edit update ]

  def edit
    if @voter.ratings.length == 0
      @voter.survey.proposals.each do |proposal|
        @voter.ratings.create(proposal: proposal)
      end
    else
      redirect_to survey_url(@voter.survey), notice: "you have voted already"
    end
  end

  def update
    respond_to do |format|
      if @voter.update(voter_params)
        format.html { redirect_to survey_url(@voter.survey), notice: "Voter was successfully updated." }
        format.json { render :show, status: :ok, location: @voter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_voter
    @voter = Voter.find_by(token: params[:token])
  end

  def voter_params
    params.require(:voter).permit(ratings_attributes: [:name, :id, :proposal_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>BestLunch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex h-100 text-center text-white bg-dark">

  <div class="container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
      <nav class="navbar navbar-dark" style="background-color: transparent;">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">BestLunch</a>
        </div>
      </nav>
    </header>

    <%= yield %>

    <footer class="mt-auto text-white-50">
      <p>
        <%= link_to "Surveys", surveys_url, class: "text-white px-2"%>
        <%= link_to "Majority judgement", "https://en.wikipedia.org/wiki/Majority_judgment", class: "text-white px-2"%>
        <a href="<%= ENV["SOURCE_CODE_URL"] %>" class="text-white px-2">Source code</a>
      </p>
    </footer>
  </div>
  </body>
</html>

app/views/surveys/_errors.html.erb
<% if survey.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

    <ul>
      <% survey.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/surveys/_form.html.erb
<%= form_with(model: survey) do |form| %>
  <% if survey.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% survey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/surveys/_proposal_fields.html.erb
<div class="proposal-nested-fields">
  <div class="input-group mb-3">
    <%= f.input_field :name, placeholder: "Name of your proposal", class: "form-control" %>
    <%= link_to_remove_association "Delete", f, wrapper_class: "proposal-nested-fields", class: "btn btn-danger" %>
  </div>
</div>

app/views/surveys/_survey.html.erb
<div id="<%= dom_id survey %>">
</div>

app/views/surveys/_voter_fields.html.erb
<div class="voter-nested-fields">
  <div class="input-group mb-3">
    <%= f.input_field :email, placeholder: "Email of your voter", class: "form-control" %>
    <%= link_to_remove_association "Delete", f, wrapper_class: "voter-nested-fields", class: "btn btn-danger" %>
  </div>
</div>

app/views/surveys/edit.html.erb
<p style="color: green"><%= notice %></p>

<main class="px-3">
  <h1 class="py-3">Editing survey</h1>

  <%= simple_form_for @survey do |form| %>
    <%= form.input :name, label: "Name of survey", placeholder: "Write your survey name here", input_html: { class: "mb-3" } %>
    <label for="survey">Proposals</label>
    <div id="proposals">
      <%= form.simple_fields_for :proposals do |proposals_form| %>
        <%= render 'proposal_fields', f: proposals_form %>
      <% end %>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-3">
        <%= link_to_add_association 'add proposal', form, :proposals, class: "btn btn-primary text-start" %>
      </div>
    </div>

    <label for="survey">Voters</label>
    <div id="voters">
      <%= form.simple_fields_for :voters do |voters_form| %>
        <%= render 'voter_fields', f: voters_form %>
      <% end %>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-3">
        <%= link_to_add_association 'add voter', form, :voters, class: "btn btn-primary text-start" %>
      </div>
    </div>

    <div class="d-grid gap-2">
      <%= form.submit "Launch survey", class: "btn btn-success" %>
    </div>
  <% end %>
</main>

app/views/surveys/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Surveys</h1>

<div id="surveys">
  <% @surveys.each do |survey| %>
    <%= render survey %>
    <p>
      <%= link_to survey.name, survey %>
    </p>
  <% end %>
</div>

<%= link_to "New survey", new_survey_path %>

app/views/surveys/new.html.erb
<main class="px-3">
  <h1 class="py-3">New survey</h1>

  <%= simple_form_for @survey, html: { class: "row row-cols-lg-auto g-3 align-items-start" } do |form| %>
    <div class="col-lg-10">
      <%= form.input :name, label: false, placeholder: "Write your survey name here", class: "form-control" %>
    </div>

    <div class="d-grid gap-2 col-lg-2 mx-auto">
      <%= form.submit "Create survey", class: "btn btn-primary" %>
    </div>
  <% end %>
</main>

app/views/surveys/show.html.erb
<p style="color: green"><%= notice %></p>

<main class="px-3">
  <div class="card">
    <div class="card-header text-dark">
      <h2><%= @survey.name %></h2>
    </div>
    <ul class="list-group list-group-flush">
      <% @survey.scores.each do |score| %>
        <li class="list-group-item">
          <h5 class="form-check-label text-start"><%= score.proposal.name %> : <%= score.name %></h5>
          <div class="progress" style="height: 25px;">
            <div class="progress-bar" role="progressbar" style="background-color: darkgreen; width: <%= score.proposal.excellent_percent %>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"><%= score.proposal.excellent_percent %>%</div>
            <div class="progress-bar" role="progressbar" style="background-color: forestgreen; width: <%= score.proposal.very_good_percent %>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"><%= score.proposal.very_good_percent %>%</div>
            <div class="progress-bar" role="progressbar" style="background-color: yellowgreen; width: <%= score.proposal.good_percent %>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"><%= score.proposal.good_percent %>%</div>
            <div class="progress-bar" role="progressbar" style="background-color: yellow; width: <%= score.proposal.passable_percent %>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"><%= score.proposal.passable_percent %>%</div>
            <div class="progress-bar" role="progressbar" style="background-color: orange; width: <%= score.proposal.inadequate_percent %>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"><%= score.proposal.inadequate_percent %>%</div>
          </div>
        </li>
      <% end %>
      <div class="card-footer">
        <div class="d-grid gap-2">
          <p class="text-dark"> Number of votes: <%= @survey.number_of_votes %> </p>
          <p class="text-dark"> Winner: <%= @survey.winner %> </p>
        </div>
      </div>
    </ul>
  </div>
</main>

app/views/voters/edit.html.erb
<p style="color: green"><%= notice %></p>

<main class="px-3">
  <div class="card my-3">
    <div class="card-header text-dark">
      <%= @voter.survey.name %>
    </div>
    <ul class="list-group list-group-flush">
      <%= simple_form_for @voter, url: voter_url(@voter.token) do |form| %>
        <%= form.simple_fields_for :ratings do |ratings_form| %>
          <li class="list-group-item d-flex justify-content-between">
            <h5 class="form-check-label"><%= ratings_form.object.proposal.name %> </h5>
            <div class="px-3">
              <%= ratings_form.hidden_field :proposal_id %>
              <%= ratings_form.collection_radio_buttons :name, Rating::NAMES, :first, :first, item_wrapper_class: "px-2" do |b| %>
                <%= b.label do %>
                  <%= b.radio_button %>
                  <div class="px-2"><%= b.text %></div>
                <% end %>
              <% end %>
            </div>
          </li>
        <% end %>
        <div class="card-footer">
          <div class="d-grid gap-2">
            <%= form.submit "Confirm my vote", class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
</main>